INSERT INTO PLAYER (PSEUDO,TOKENS) VALUES ('Pseudo1',4);

INSERT INTO CARDS_PACK (TYPE,REQUIRED_TOKENS,CARDS_NUMBER,LEGENDARY_DROP_RATE,RARE_DROP_RATE,COMMON_DROP_RATE) VALUES ('Diamant',2,5,0.15,0.35,0.5);
INSERT INTO CARDS_PACK (TYPE,REQUIRED_TOKENS,CARDS_NUMBER,LEGENDARY_DROP_RATE,RARE_DROP_RATE,COMMON_DROP_RATE) VALUES ('Argent',1,3,0.05,0.2,0.75);

INSERT INTO HERO (NAME,SPECIALTY,RARITY,HP,XP,POWER,ARMOR,LEVEL) VALUES ('Hero1','Tank','Legendary',1200,0,120,24,1);
INSERT INTO HERO (NAME,SPECIALTY,RARITY,HP,XP,POWER,ARMOR,LEVEL) VALUES ('Hero2','Tank','Rare',1100,0,110,22,1);
INSERT INTO HERO (NAME,SPECIALTY,RARITY,HP,XP,POWER,ARMOR,LEVEL) VALUES ('Hero3','Tank','Common',1000,0,100,20,1);

INSERT INTO DECK (ID_PLAYER) VALUES (1);